server:
  http2:
    enabled: true

graphql:
  servlet:
    exception-handlers-enabled: false
    tracing-enabled: true
  playground:
    headers:
      Auth: Bearer TOKEN
      User: Sumfi
    tabs:
      - name: WebToon sample query
        query: classpath:graphql/playground/webtoon_query.graphql
        variables: classpath:graphql/playground/webtoon_query_variables.json
      - name: WebToon sample mutation
        query: classpath:graphql/playground/webtoon_mutation.graphql
        variables: classpath:graphql/playground/webtoon_mutation_variables.json
    settings:
      request:
        credentials: include

spring:
  servlet:
    multipart:
      max-file-size: 1MB

logging:
  pattern:
    console: ${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%X{correlation_id}){red} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

